/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AICalendar: typeof import('./src/components/calendar/main/AICalendar.vue')['default']
    AICalendarButton: typeof import('./src/components/calendar/button/AICalendarButton.vue')['default']
    AppIcon: typeof import('./src/components/icon/AppIcon.vue')['default']
    AppSetting: typeof import('./src/components/setting/AppSetting.vue')['default']
    ArchivedDataSetting: typeof import('./src/components/setting/ArchivedDataSetting.vue')['default']
    Chat: typeof import('./src/components/chat/main/Chat.vue')['default']
    ChatBody: typeof import('./src/components/chat/body/ChatBody.vue')['default']
    ChatBodyEmpty: typeof import('./src/components/chat/body/ChatBodyEmpty.vue')['default']
    ChatBodyHeader: typeof import('./src/components/chat/body/ChatBodyHeader.vue')['default']
    ChatBodyInput: typeof import('./src/components/chat/body/ChatBodyInput.vue')['default']
    ChatBodyMessageList: typeof import('./src/components/chat/body/ChatBodyMessageList.vue')['default']
    ChatBodyPrompt: typeof import('./src/components/chat/body/ChatBodyPrompt.vue')['default']
    ChatBodyScreenshotList: typeof import('./src/components/chat/body/ChatBodyScreenshotList.vue')['default']
    ChatBodySetting: typeof import('./src/components/chat/body/ChatBodySetting.vue')['default']
    ChatBodyShare: typeof import('./src/components/chat/body/ChatBodyShare.vue')['default']
    ChatBodyShareView: typeof import('./src/components/chat/body/ChatBodyShareView.vue')['default']
    ChatBodyStatistic: typeof import('./src/components/chat/body/ChatBodyStatistic.vue')['default']
    ChatMessageAssistant: typeof import('./src/components/chat/message/ChatMessageAssistant.vue')['default']
    ChatMessageConsole: typeof import('./src/components/chat/message/ChatMessageConsole.vue')['default']
    ChatMessageDivider: typeof import('./src/components/chat/message/ChatMessageDivider.vue')['default']
    ChatMessageError: typeof import('./src/components/chat/message/ChatMessageError.vue')['default']
    ChatMessageUser: typeof import('./src/components/chat/message/ChatMessageUser.vue')['default']
    ChatSidebar: typeof import('./src/components/chat/sidebar/ChatSidebar.vue')['default']
    ChatSidebarFooter: typeof import('./src/components/chat/sidebar/ChatSidebarFooter.vue')['default']
    ChatSidebarHeader: typeof import('./src/components/chat/sidebar/ChatSidebarHeader.vue')['default']
    ChatSidebarSession: typeof import('./src/components/chat/sidebar/ChatSidebarSession.vue')['default']
    ChatSidebarSessionList: typeof import('./src/components/chat/sidebar/ChatSidebarSessionList.vue')['default']
    FileIcon: typeof import('./src/components/icon/FileIcon.vue')['default']
    MemoryDataSetting: typeof import('./src/components/setting/MemoryDataSetting.vue')['default']
    MoreButton: typeof import('./src/components/more/button/MoreButton.vue')['default']
    MorePage: typeof import('./src/components/more/main/MorePage.vue')['default']
    NoteEditor: typeof import('./src/components/calendar/editor/NoteEditor.vue')['default']
    TitleBar: typeof import('./src/components/title/TitleBar.vue')['default']
  }
}
